name: pm2 build on change

on: 
  push:
    branches:
      - master
      - main
      - adding-multiarch
    workflow_dispatch:
    repository_dispatch:
      types: pm2 

jobs:
  pm2:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: building pm2 and deploying to docker
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker build -t treehouses/pm2 .
          docker push treehouses/pm2
