name: pm2 build on change

on: 
  push:
    branches:
      - master
      - main
      - adding-multiarch
    workflow_dispatch:
    repository_dispatch:
      types: pm2 

jobs:
  pm2:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: building pm2 and deploying to docker
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="treehouses/pm2"
          source .github/workflows/utils.sh
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          build_image "treehouses/node:latest" arm "$repo"
          build_image "treehouses/node:latest" amd64 "$repo"
          build_image "treehouses/node:latest" arm64 "$repo"
          deploy_image "$repo" arm
          deploy_image "$repo" amd64
          deploy_image "$repo" arm64
          tag=$(date +%Y%m%d%H%M)
          tag2="latest"
          echo $tag
          create_manifest $repo $tag $tag2 $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
          docker manifest inspect $repo:$tag
          docker manifest inspect $repo:$tag2
          if [[ $flag == true ]]; then
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi

          
