name: pm2

on: [push]

jobs:
  pm2-build:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm, arm64, amd64]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: building pm2 
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          docker buildx build --platform linux/${{ matrix.arch }} -t treehouses/pm2:${{ matrix.arch }} .
          docker push treehouses/pm2:${{ matrix.arch }}
  pm2-manifest:
    needs: pm2-build
    runs-on: ubuntu-20.04
    steps:
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: deploying to docker
        run: |
          docker manifest create treehouses/pm2:latest treehouses/pm2:amd64 treehouses/pm2:arm treehouses/pm2:arm64
          docker manifest inspect treehouses/pm2:latest
          docker manifest annotate treehouses/pm2:latest treehouses/pm2:arm --variant arm
          docker manifest inspect treehouses/pm2:latest
          docker manifest push treehouses/pm2:latest
